### ISSUE TITLE
v0.11.0

### ISSUE THREAD

**Issue by EarlyH** [Morning-UI/morning-ui#172]
- [x] #314 文档改版
- [x] #149 新增 `ui-slider`滑块
- [x] #141 新增 `ui-video` 视频组件
- [x] #174 新增 `ui-audio` 音频组件
- [x] #48 新增 `ui-sticky` 滚动跟随组件 
- [x] #175 新增 `ui-colorpicker` 取色器
- [x] #182 新增 `ui-textediter` 富文本输入
- [x] #249 `ui-textinput`的`prepend`和`append`支持行内样式
- [x] #255 `ui-textarea`支持自动调整高度
- [x]  #307 `ui-switch`优化form-name的展示、增加左右显示的文字、增加内部文字
- [x] #270 `ui-checkbox`禁用部分选项、新增带边框样式、支持最多可选数量、新增垂直布局
- [x] #316 `ui-checkbox`支持联动
- [x] #271 `ui-radio`禁用部分选项、新增带边框样式、支持垂直布局
- [x] #256 `ui-breadcrumbs`支持修改分隔图标
- [x] #283 `ui-tab`样式优化、支持位置改变、支持按钮式标签页
- [x] #258 `ui-btn`支持更多形状
- [x] #309 `ui-select`选中项有打勾的icon
- [x] #264 全局加载动画更新
- [x] #294 增加更多常见UI库对比，并新增对比的版本号
- [x] #259 支持icon
- [x] #292  全局事件管理支持`hashchange`事件
- [x] #289 更新日志格式支持分类
- [x] #323 优化formgroup中文字的大小
- [x] #324 ui-datepicker和ui-datetimepicker增加done-hidden配置
- [x] #329 `ui-select`支持异步搜索加载数据

0.11.0版本将在6月22日发布。
